const experience = [
  {
    id: 1,
    title: "Software Engineer",
    startDate: "June 1, 2024",
    endDate: "",
    image: "symbotic",
  },
  {
    id: 2,
    title: "Test Automation Engineer Co-op",
    startDate: "July 10, 2023",
    endDate: "December 20, 2023",
    image: "symbotic",
  },
  {
    id: 3,
    title: "Software Engineer Co-op",
    startDate: "July 10, 2022",
    endDate: "December 20, 2022",
    image: "highresbio",
  },
  {
    id: 4,
    title: "Software Technical Lead",
    startDate: "December 20, 2023",
    endDate: "April 20, 2024",
    image: "generate",
  },
  {
    id: 5,
    title: "Software Engineer",
    startDate: "September 20, 2023",
    endDate: "December 20, 2023",
    image: "generate",
  },
  {
    id: 6,
    title: "Teaching Assistant & Lab Lead - CS2510",
    startDate: "January 20, 2022",
    endDate: "April 20, 2022",
    image: "khoury",
  },
  {
    id: 7,
    title: "Teaching Assistant - CS2500",
    startDate: "September 20, 2021",
    endDate: "December 20, 2021",
    image: "khoury",
  },
];

const projects = [
  {
    id: 1,
    title: "Care-Wallet",
    position: "Software Technical Lead",
    organization: "Generate",
    startDate: "December 20, 2023",
    endDate: "April 20, 2024",
    image: "generate",
    githuburl: "",
    description: "",
  },
  {
    id: 2,
    title: "Generate Website",
    position: "Software Engineer",
    organization: "Generate",
    startDate: "September 10, 2023",
    endDate: "December 20, 2023",
    image: "generate",
    githuburl: "",
    description: "",
  },
  {
    id: 3,
    title: "Streaming Availability",
    position: "",
    organization: "",
    startDate: "February 20, 2024",
    endDate: "April 20, 2024",
    image: "",
    githuburl: "",
    description: "",
  },
  {
    id: 4,
    title: "Portfolio V1",
    position: "",
    organization: "",
    startDate: "July 10, 2022",
    endDate: "December 20, 2022",
    image: "",
    githuburl: "",
    description: "",
  },
  {
    id: 5,
    title: "Portfolio V2",
    position: "",
    organization: "",
    startDate: "April 24, 2024",
    endDate: "",
    image: "",
    githuburl: "",
    description: "",
  },
  {
    id: 6,
    title: "Covey.Town - Checkers",
    position: "",
    organization: "",
    startDate: "January 20, 2023",
    endDate: "April 24, 2023",
    image: "",
    githuburl: "",
    description: "",
  },
  {
    id: 7,
    title: "Agar.IO Clone",
    position: "",
    organization: "",
    startDate: "September 20, 2021",
    endDate: "November 20, 2021",
    image: "",
    githuburl: "",
    description: "",
  },
];

const education = [
  {
    id: 1,
    school: "Northeastern University",
    degree: "Bachelor of Science in Computer Science",
    gpa: 3.5,
    endDate: "May 1, 2024",
    image: "northeastern",
  },
];

export const StaticJSONDatabase = {
  experience,
  projects,
  education,
};
